'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Reproductor_3._0_DVD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property base() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("base", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property base___copia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("base___copia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property baseCompac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseCompac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property baseCompac___copia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseCompac___copia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property baseCompac1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseCompac1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bass() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bass", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Public ReadOnly Property btnAbrir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAbrir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnAbrirMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAbrirMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnAnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnAntMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAntMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnAudio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAudio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnAudioMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAudioMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnCarp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCarp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnCarpMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCarpMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnCloseMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCloseMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnComp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnComp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnCompMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCompMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnDVD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDVD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnDVDMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDVDMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnExp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnExp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnExpMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnExpMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnGen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnGen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnGen2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnGen2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnGenMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnGenMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnLis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnLisMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLisMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnLugCarp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLugCarp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnLugCarpMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLugCarpMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnLugLis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLugLis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnLugLisMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLugLisMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnMin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnMinMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMinMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnModoRep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnModoRep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnModoRepMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnModoRepMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnModoRepUn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnModoRepUn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnOpc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOpc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnOpcMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOpcMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnOrden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOrden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnOrdenMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOrdenMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnParar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnParar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnPararMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPararMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnPau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnPauMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPauMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnRadio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRadio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnRadioMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRadioMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnRepOnMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRepOnMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnRepro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRepro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnReproMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnReproMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSigMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSigMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSobre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSobre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSobreMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSobreMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSpk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSpk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSpkMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSpkMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSpkMut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSpkMut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btnSpkMutMov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSpkMutMov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dspNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dspNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dspPause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dspPause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dspPlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dspPlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dspPrev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dspPrev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dspStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dspStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ico_disco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_disco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property icoActivo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icoActivo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property icoartista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoartista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property icoAudio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoAudio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property icoInactivo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icoInactivo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property icoPrincipal() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icoPrincipal", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property icoVideo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoVideo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgmodnorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgmodnorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgmodrepAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgmodrepAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgmodrepl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgmodrepl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgordnorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgordnorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgordrnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgordrnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgsrcCarp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgsrcCarp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property imgsrcLista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgsrcLista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property minibase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minibase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property minibasetrans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minibasetrans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property MSWINSCK() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MSWINSCK", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Public ReadOnly Property popClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popInf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popInf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popKey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popKey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popKeyen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popKeyen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popPlPA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popPlPA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popPrev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popPrev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property popStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property RadioTuner() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RadioTuner", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Public ReadOnly Property secundary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("secundary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property thAnt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("thAnt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property thParar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("thParar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property thPau() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("thPau", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property thRepro() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("thRepro", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property thSig() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("thSig", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
